Repository wecode-bootcamp-korea/32-1st-boyFriends-backend, pull requests merged in 2022-05, with the labels that each got.

#8 refactor:Fix image table
  products/migrations/0006_alter_image_review.py
Labels: Status: Accepted

#7 feat: login decorator
  core/utils.py
Labels: Status: Accepted

#6 feat: Create SignInView & url setting
  users/urls.py
  users/views.py
Labels: Status: Accepted

#10 Fix: typo correction
  boyfriends/settings.py
  core/utils.py
Labels: Status: Accepted

#12 Fix : carts table attribute, images table attribute
  payments/migrations/0007_cart_check_box.py
  payments/models.py
  products/migrations/0007_alter_image_product.py
  products/models.py
Labels: Status: Accepted

#13 refactor: Fix : image table attribute
  products/migrations/0008_image_category.py
  products/models.py
Labels: Status: Accepted

#16 Add field option to cart
  payments/migrations/0008_cart_option.py
  payments/models.py
Labels: Status: Accepted

#20 Feature/identification decorator
  core/utils.py
Labels: Status: 리뷰 요청

#19 Feature/navigation
  boyfriends/urls.py
  core/urls.py
  core/views.py
Labels: Status: 리뷰 요청

#14 Feature/cart
  .idea/misc.xml
  boyfriends/urls.py
  payments/urls.py
  payments/views.py
Labels: Status: 리뷰 요청

#17 Feature :Create topicview
  boyfriends/urls.py
  core/views.py
  products/urls.py
  products/views.py
Labels: Status: 수정 요청

#15 Feature/review
  boyfriends/urls.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#11 Feature/product detail
  boyfriends/urls.py
  products/urls.py
  products/views.py
Labels: Status: 리뷰 요청

#9 Feature/products list
  .idea/.gitignore
  .idea/32-1st-boyFriends-backend.iml
  .idea/inspectionProfiles/Project_Default.xml
  .idea/inspectionProfiles/profiles_settings.xml
  .idea/modules.xml
  .idea/vcs.xml
  boyfriends/urls.py
  products/urls.py
  products/views.py
  requirements.txt
Labels: Status: 수정 요청
